version: "3.9"
services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    ports:
      - '3307:3306'
  psql:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: $PG_USERNAME
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: test
    ports:
      - '5432:5432'
  ydb-local:
    image: cr.yandex/yc/yandex-docker-local-ydb:latest
    restart: unless-stopped
    ports:
      - '2136:2136'
      - '2135:2135'
      - '8765:8765'
    volumes:
      - 'ydb_certs:/ydb_certs'
      - 'ydb_data:/ydb_data'
    hostname: localhost
    environment:
      YDB_DEFAULT_LOG_LEVEL: NOTICE
      GRPC_TLS_PORT: 2135
      GRPC_PORT: 2136
      MON_PORT: 8765
volumes:
  ydb_certs:
  ydb_data: