name: test_coverage

on: [push]


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    env:
      COMPOSE_FILE: docker-compose.yml
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DATABASE: test
      PG_USERNAME: pguser
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: Build images
        run: docker-compose -f $COMPOSE_FILE up -d

      - name: Check running containers
        run: docker ps -a

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          make venv

      - name: build coverage ubuntu
        run: |
          make test

      - name: stop containers
        run: docker-compose stop